### ISSUE TITLE
Use of MolarMass is Unnecessarily Complicated

### ISSUE THREAD

**Issue by KingJMS1** [oasisks/Chemistry-Application-Rework#4]
### Problematic Behavior:
`
mass = MolarMass("C6H12O6", kg=false)
`
then if I actually want the molar mass, I have to run:
`
mass = float(mass)
`

### Suggestion:
Simplify the calculation of Molar Mass as follows:
`
mass = MolarMass("C6H12O6", kg=false)
`
where mass is simply the molar mass, as expected.

This would make MolarMass much more intuitive and simplify programming requiring the molar mass of compounds.

**Comment by KingJMS1** [comment]
In fact, now that the Compound class exists, it would make sense to implement it like this:
### Modified Suggestion
```
compound = Compound("C6H12O6")
mass = compound.molarMass()
```

**Comment by oasisks** [comment]
The Compound class now has a function that calculates the molar mass of a compound. It also has the ability to calculate the percent abundance of each element within the compound now too. 
```compound = Compound("C6H12O6")
mass = compound.molarMass()
percentComposition = compound.percentComposition()
